module.exports = [
    'British',
    'Steak',
    'Steakhouse',
    'Japanese',
    'Italian',
    'Pan-Asian',
    'French',
    'American',
    'Deli',
    'Global',
    'International',
    'Californian',
    'Tapas / Small Plates',
    'Spanish',
    'Modern European',
    'Asian',
    'Indian',
    'Pizzeria',
    'Contemporary British',
    'Vegan',
    'Burgers',
    'Wine Bar',
    'Contemporary Asian',
    'Chinese',
    'Portuguese',
    'Mediterranean',
    'Chinese (Canton)',
    'Seafood',
    'Bar / Lounge / Bottle Service',
    'Lebanese',
    'Thai',
    'Gastro Pub',
    'International',
    'Pub',
    'European',
    'English',
    'Pizza Bar',
    'Korean'
]