export const foodTypes = [
    { label: 'British', value: 'British', id: 0 },
    { label: 'Steak', value: 'Steak', id: 1 },
    { label: 'Steakhouse', value: 'Steakhouse', id: 2 },
    { label: 'Japanese', value: 'Japanese', id: 3 },
    { label: 'Italian', value: 'Italian', id: 4 },
    { label: 'Pan-Asian', value: 'Pan-Asian', id: 5 },
    { label: 'French', value: 'French', id: 6 },
    { label: 'American', value: 'American', id: 7 },
    { label: 'Deli', value: 'Deli', id: 8 },
    { label: 'Global', value: 'Global', id: 9 },
    { label: 'International', value: 'International', id: 10 },
    { label: 'Californian', value: 'Californian', id: 11 },
    { label: 'Tapas / Small Plates', value: 'Tapas / Small Plates', id: 12 },
    { label: 'Spanish', value: 'Spanish', id: 13 },
    { label: 'Modern European', value: 'Modern European', id: 14 },
    { label: 'Asian', value: 'Asian', id: 15 },
    { label: 'Indian', value: 'Indian', id: 16 },
    { label: 'Pizzeria', value: 'Pizzeria', id: 17 },
    { label: 'Contemporary British', value: 'Contemporary British', id: 18 },
    { label: 'Vegan', value: 'Vegan', id: 19 },
    { label: 'Burgers', value: 'Burgers', id: 20 },
    { label: 'Wine Bar', value: 'Wine Bar', id: 21 },
    { label: 'Contemporary Asian', value: 'Contemporary Asian', id: 22 },
    { label: 'Chinese', value: 'Chinese', id: 23 },
    { label: 'Portuguese', value: 'Portuguese', id: 24 },
    { label: 'Mediterranean', value: 'Mediterranean', id: 25 },
    { label: 'Chinese (Canton)', value: 'Chinese (Canton)', id: 26 },
    { label: 'Seafood', value: 'Seafood', id: 27 },
    { label: 'Bar / Lounge / Bottle Service', value: 'Bar / Lounge / Bottle Service', id: 28 },
    { label: 'Lebanese', value: 'Lebanese', id: 29 },
    { label: 'Thai', value: 'Thai', id: 30 },
    { label: 'Gastro Pub', value: 'Gastro Pub', id: 31 },
    { label: 'International', value: 'International', id: 32 },
    { label: 'Pub', value: 'Pub', id: 33 },
    { label: 'European', value: 'European', id: 34 },
    { label: 'English', value: 'English', id: 35 },
    { label: 'Pizza Bar', value: 'Pizza Bar', id: 36 },
    { label: 'Korean', value: 'Korean', id: 37 }
]