export const foodTypesToLabel = {
    British: 'British',
    Steak: 'Steak',
    Steakhouse: 'Steakhouse',
    Japanese: 'Japanese',
    Italian: 'Italian',
    'Pan-Asian': 'Pan-Asian',
    French: 'French',
    American: 'American',
    Deli: 'Deli',
    Global: 'Global',
    International: 'International',
    Californian: 'Californian',
    'Tapas / Small Plates': 'Tapas / Small Plates',
    Spanish: 'Spanish',
    'Modern European': 'Modern European',
    Asian: 'Asian',
    Indian: 'Indian',
    Pizzeria: 'Pizzeria',
    'Contemporary British': 'Contemporary British',
    Vegan: 'Vegan',
    Burgers: 'Burgers',
    'Wine Bar': 'Wine Bar',
    'Contemporary Asian': 'Contemporary Asian',
    Chinese: 'Chinese',
    Portuguese: 'Portuguese',
    Mediterranean: 'Mediterranean',
    'Chinese (Canton)': 'Chinese (Canton)',
    Seafood: 'Seafood',
    'Bar / Lounge / Bottle Service': 'Bar / Lounge / Bottle Service',
    Lebanese: 'Lebanese',
    Thai: 'Thai',
    'Gastro Pub': 'Gastro Pub',
    Pub: 'Pub',
    European: 'European',
    English: 'English',
    'Pizza Bar': 'Pizza Bar',
    Korean: 'Korean'
  }