insert into restaurants (name, price, type, rating, image_source) values ('Hypnum Moss', '££££', 'michelin', 4.8, 'http://dummyimage.com/206x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Sour Orange', '£££', 'indian', 4.3, 'http://dummyimage.com/151x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Rimmed Lichen', '££££', 'indian', 1.7, 'http://dummyimage.com/205x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Carretilla', '£', 'greek', 2.7, 'http://dummyimage.com/222x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Threelocule Corchorus', '£££', 'french', 3.2, 'http://dummyimage.com/240x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Merismatium Lichen', '£', 'seafood', 3.4, 'http://dummyimage.com/167x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cornutia', '££', 'seafood', 1.9, 'http://dummyimage.com/148x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Pseudophrenula Lichen', '£', 'greek', 4.5, 'http://dummyimage.com/151x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('House Range Primrose', '£££', 'greek', 4.2, 'http://dummyimage.com/137x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Orange Wall Lichen', '£', 'cocktail', 4.2, 'http://dummyimage.com/193x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cyanic Milkvetch', '££', 'fast-food', 1.8, 'http://dummyimage.com/123x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hawthorn', '£££', 'japanese', 4.6, 'http://dummyimage.com/206x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cooper''s Rubberweed', '££', 'steak', 4.8, 'http://dummyimage.com/245x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Rough Hawksbeard', '£', 'english', 3.9, 'http://dummyimage.com/213x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Manchurian Wildrice', '£££', 'hot-pot', 3.7, 'http://dummyimage.com/218x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Bull Withe', '£££', 'fine-dining', 4.3, 'http://dummyimage.com/195x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Wooton''s Sandpuffs', '£', 'japanese', 2.2, 'http://dummyimage.com/190x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Snakecotton', '£', 'greek', 3.4, 'http://dummyimage.com/103x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Matted Grama', '££££', 'cocktail', 2.2, 'http://dummyimage.com/189x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Comb Forkedfern', '££', 'indian', 2.1, 'http://dummyimage.com/133x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Fremont''s Goldfields', '£', 'indian', 4.9, 'http://dummyimage.com/126x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Sweet Wakerobin', '££', 'michelin', 2.5, 'http://dummyimage.com/181x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Oregon Coolwort', '££££', 'hot-pot', 4.5, 'http://dummyimage.com/178x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cuban Copperleaf', '££££', 'steak', 4.7, 'http://dummyimage.com/246x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Eremocitrus', '££', 'hot-pot', 3.9, 'http://dummyimage.com/155x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Sedge', '££££', 'michelin', 4.3, 'http://dummyimage.com/196x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cephaelis', '£££', 'michelin', 3.1, 'http://dummyimage.com/190x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Grassland Tarweed', '£', 'english', 1.1, 'http://dummyimage.com/190x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Texas Venus'' Looking-glass', '££££', 'japanese', 2.3, 'http://dummyimage.com/215x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Red Currant', '££', 'italian', 3.8, 'http://dummyimage.com/139x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Statice', '£££', 'greek', 4.2, 'http://dummyimage.com/234x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Olympic Bellflower', '£', 'japanese', 2.0, 'http://dummyimage.com/125x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Oakes'' Evening Primrose', '£££', 'hot-pot', 3.6, 'http://dummyimage.com/239x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Neomacounia Moss', '££££', 'steak', 1.7, 'http://dummyimage.com/176x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Toano Milkvetch', '££', 'pizza', 2.6, 'http://dummyimage.com/228x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Hybrid Rose', '££££', 'greek', 2.5, 'http://dummyimage.com/201x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Charleston Mountain Draba', '££££', 'italian', 4.3, 'http://dummyimage.com/101x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Texas Palafox', '££££', 'cocktail', 2.9, 'http://dummyimage.com/179x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lycaste', '£', 'greek', 1.5, 'http://dummyimage.com/130x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Alpine Draba', '££', 'indian', 1.5, 'http://dummyimage.com/168x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Carolina Hawthorn', '££££', 'italian', 2.0, 'http://dummyimage.com/160x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Poodle-dog Bush', '££££', 'greek', 1.3, 'http://dummyimage.com/126x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Vervain', '£', 'english', 2.4, 'http://dummyimage.com/155x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Chalice Lichen', '££££', 'italian', 2.1, 'http://dummyimage.com/187x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Goatbush', '£', 'fast-food', 1.4, 'http://dummyimage.com/119x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hippeastrum', '££', 'french', 3.0, 'http://dummyimage.com/170x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Eve''s Necklacepod', '£££', 'hot-pot', 1.8, 'http://dummyimage.com/245x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Texas Wedgescale', '£££', 'indian', 2.3, 'http://dummyimage.com/138x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Flatsedge', '£££', 'chinese', 2.6, 'http://dummyimage.com/115x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Mustang Clover', '££', 'fast-food', 3.4, 'http://dummyimage.com/119x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Fire Vine', '££££', 'fine-dining', 4.9, 'http://dummyimage.com/151x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Koolau Range Colicwood', '£', 'english', 3.8, 'http://dummyimage.com/160x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Century Plant', '£', 'fast-food', 2.8, 'http://dummyimage.com/170x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Knight''s Milkvetch', '£££', 'steak', 3.2, 'http://dummyimage.com/135x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Wart Lichen', '££', 'steak', 4.1, 'http://dummyimage.com/166x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Manyflower Sunflower', '££', 'fine-dining', 2.8, 'http://dummyimage.com/247x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cochise Rockdaisy', '£££', 'japanese', 1.5, 'http://dummyimage.com/100x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Geophila', '££', 'michelin', 4.1, 'http://dummyimage.com/120x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Grand Fringed Gentian', '££', 'italian', 3.9, 'http://dummyimage.com/115x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Noble Fir', '££££', 'fine-dining', 1.2, 'http://dummyimage.com/151x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Virginia Heartleaf', '££££', 'italian', 4.2, 'http://dummyimage.com/206x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Recurved Blackberry', '£', 'japanese', 3.5, 'http://dummyimage.com/141x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('American Dunegrass', '£££', 'french', 3.3, 'http://dummyimage.com/196x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('California Popcornflower', '££££', 'cocktail', 3.4, 'http://dummyimage.com/221x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Alpine Knapweed', '£££', 'michelin', 2.5, 'http://dummyimage.com/170x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Limestone Swamp Bedstraw', '£££', 'italian', 2.5, 'http://dummyimage.com/226x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Upland Larkspur', '£', 'french', 1.6, 'http://dummyimage.com/213x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lecidea Lichen', '£££', 'cocktail', 4.5, 'http://dummyimage.com/181x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Silkyleaf Cinquefoil', '££', 'hot-pot', 4.6, 'http://dummyimage.com/206x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Clavel De Muerto', '£', 'indian', 1.6, 'http://dummyimage.com/169x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Erect Cinquefoil', '£', 'chinese', 2.9, 'http://dummyimage.com/168x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Maackia', '£', 'indian', 5.0, 'http://dummyimage.com/223x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Japanese Meadowsweet', '££', 'english', 2.9, 'http://dummyimage.com/143x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Bay Biscayne Creeping-oxeye', '££££', 'seafood', 1.7, 'http://dummyimage.com/205x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Field Restharrow', '££££', 'hot-pot', 4.2, 'http://dummyimage.com/209x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Kern County Larkspur', '££', 'michelin', 1.8, 'http://dummyimage.com/198x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Moreton Bay Pine', '££', 'italian', 4.6, 'http://dummyimage.com/174x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Angularfruit Ma''oloa', '££', 'cocktail', 3.9, 'http://dummyimage.com/236x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Low Sphagnum', '£', 'seafood', 1.9, 'http://dummyimage.com/117x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Jack In The Pulpit', '££', 'cocktail', 3.5, 'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Buckwheat Tree', '££', 'english', 3.7, 'http://dummyimage.com/230x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Golden Lipfern', '££', 'indian', 3.2, 'http://dummyimage.com/238x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Arbol De Navidad', '££', 'cocktail', 4.3, 'http://dummyimage.com/176x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hairy Cyanea', '££', 'chinese', 3.1, 'http://dummyimage.com/213x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Douglas'' Silverpuffs', '£££', 'michelin', 4.5, 'http://dummyimage.com/112x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Balsamroot', '£££', 'michelin', 3.6, 'http://dummyimage.com/164x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Platydesma', '££', 'fast-food', 3.8, 'http://dummyimage.com/181x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Capitate Sedge', '££££', 'steak', 2.1, 'http://dummyimage.com/144x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Candelabra Tree', '££££', 'italian', 3.1, 'http://dummyimage.com/162x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Mohr''s Threeawn', '££', 'hot-pot', 4.9, 'http://dummyimage.com/124x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Florida Milkpea', '££££', 'indian', 1.5, 'http://dummyimage.com/218x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Whitewoolly Buckwheat', '££', 'pizza', 4.0, 'http://dummyimage.com/128x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Joshua Tree', '££££', 'pizza', 1.9, 'http://dummyimage.com/108x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Garden Tomato', '££', 'cocktail', 1.9, 'http://dummyimage.com/116x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('San Diego Wirelettuce', '££££', 'seafood', 2.6, 'http://dummyimage.com/115x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cap Lichen', '£', 'fine-dining', 5.0, 'http://dummyimage.com/215x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Havard''s Plum', '£££', 'greek', 3.6, 'http://dummyimage.com/183x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Flower Of Stone', '££', 'chinese', 4.0, 'http://dummyimage.com/166x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('West Indian Flatsedge', '££', 'michelin', 4.2, 'http://dummyimage.com/155x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Wax Palm', '££', 'japanese', 4.7, 'http://dummyimage.com/245x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Arctic Seashore Willow', '££££', 'steak', 3.6, 'http://dummyimage.com/211x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Ionaspis Lichen', '£', 'steak', 1.7, 'http://dummyimage.com/170x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cracked Lichen', '£££', 'seafood', 1.4, 'http://dummyimage.com/248x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Fragile Maidenhair', '££', 'japanese', 3.8, 'http://dummyimage.com/102x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Yerba De Guava', '££', 'steak', 3.8, 'http://dummyimage.com/231x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Musky Stork''s Bill', '£', 'italian', 3.2, 'http://dummyimage.com/118x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Tiger Grass', '££', 'steak', 3.5, 'http://dummyimage.com/144x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Flatface Calicoflower', '£', 'hot-pot', 1.8, 'http://dummyimage.com/170x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Bladderwort', '££££', 'italian', 3.4, 'http://dummyimage.com/174x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cliffdweller', '£££', 'indian', 1.9, 'http://dummyimage.com/231x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Goatbush', '£££', 'french', 4.0, 'http://dummyimage.com/148x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Yellow Unicorn-plant', '£', 'indian', 4.4, 'http://dummyimage.com/163x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Cowhage Cherry', '££££', 'steak', 4.9, 'http://dummyimage.com/162x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hudson''s Air Fern', '£££', 'michelin', 4.3, 'http://dummyimage.com/192x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Brown Stringybark', '£', 'greek', 2.2, 'http://dummyimage.com/129x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Quick''s Phacelia', '£', 'steak', 1.9, 'http://dummyimage.com/176x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pink Turtlehead', '££££', 'japanese', 4.3, 'http://dummyimage.com/249x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Dyer''s Woad', '£££', 'hot-pot', 2.0, 'http://dummyimage.com/194x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hawthorn', '££££', 'japanese', 4.1, 'http://dummyimage.com/244x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Squirrel''s Tail', '££££', 'pizza', 2.5, 'http://dummyimage.com/243x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lance Asplenium', '££££', 'japanese', 3.4, 'http://dummyimage.com/214x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Langsdorf''s Lousewort', '££££', 'cocktail', 4.0, 'http://dummyimage.com/105x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Alamovine', '££', 'italian', 4.0, 'http://dummyimage.com/127x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Tulip Pricklypear', '££££', 'greek', 4.4, 'http://dummyimage.com/111x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hyssopleaf Thoroughwort', '£', 'steak', 3.6, 'http://dummyimage.com/102x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('San Luis Obispo Sedge', '£', 'english', 2.6, 'http://dummyimage.com/150x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Jeweled Blazingstar', '££££', 'chinese', 1.9, 'http://dummyimage.com/162x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Pineland Nailwort', '££', 'chinese', 3.0, 'http://dummyimage.com/190x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Laurel-leaf Swordfern', '£££', 'hot-pot', 1.1, 'http://dummyimage.com/208x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Rocky Mountain Aster', '££', 'pizza', 1.0, 'http://dummyimage.com/125x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Styphelia', '£', 'chinese', 3.7, 'http://dummyimage.com/228x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Hooker''s Sandwort', '£', 'french', 1.1, 'http://dummyimage.com/178x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hairy Jointvetch', '££££', 'english', 4.2, 'http://dummyimage.com/239x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Great Lakes Sandcherry', '££', 'english', 3.5, 'http://dummyimage.com/132x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pecho Manzanita', '£££', 'steak', 1.9, 'http://dummyimage.com/111x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Sessileleaf Pinelandcress', '££', 'seafood', 5.0, 'http://dummyimage.com/168x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Laurel', '£££', 'hot-pot', 1.8, 'http://dummyimage.com/115x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Green Rabbitbrush', '££', 'seafood', 2.6, 'http://dummyimage.com/200x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lapland Reedgrass', '££££', 'french', 4.8, 'http://dummyimage.com/126x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Badlands Mule-ears', '££££', 'indian', 1.6, 'http://dummyimage.com/110x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Ferntree', '£££', 'italian', 3.8, 'http://dummyimage.com/146x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('San Bernardino Spineflower', '£££', 'seafood', 2.4, 'http://dummyimage.com/218x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Catalpa', '££', 'pizza', 4.4, 'http://dummyimage.com/175x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Urban''s Flatsedge', '££', 'indian', 2.6, 'http://dummyimage.com/223x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Coast Phacelia', '££££', 'indian', 4.2, 'http://dummyimage.com/179x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Saguaro', '£', 'cocktail', 1.1, 'http://dummyimage.com/104x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Spoonleaf Treebine', '£££', 'seafood', 1.4, 'http://dummyimage.com/190x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Ghost Orchid', '£', 'seafood', 1.2, 'http://dummyimage.com/235x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Cronquist''s Fleabane', '£', 'chinese', 2.6, 'http://dummyimage.com/127x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Mycoporum Lichen', '£££', 'italian', 4.3, 'http://dummyimage.com/202x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Preuss'' Milkvetch', '££££', 'fast-food', 1.0, 'http://dummyimage.com/177x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Hapeman''s Coolwort', '££', 'steak', 2.2, 'http://dummyimage.com/224x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Mediterranean Sweetclover', '££', 'steak', 4.0, 'http://dummyimage.com/241x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Tall Horned Beaksedge', '£££', 'fast-food', 3.7, 'http://dummyimage.com/188x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Luquillo Mountain Hempvine', '£££', 'cocktail', 4.0, 'http://dummyimage.com/156x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Trans-pecos Desert Goldenrod', '£', 'seafood', 1.0, 'http://dummyimage.com/206x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Tansy Cinquefoil', '££££', 'italian', 3.2, 'http://dummyimage.com/202x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Dorstenia', '££', 'hot-pot', 1.7, 'http://dummyimage.com/191x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('American Vetch', '££', 'chinese', 2.2, 'http://dummyimage.com/126x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Plummer''s Candyleaf', '£££', 'hot-pot', 3.1, 'http://dummyimage.com/202x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Nuttall''s Meadowbeauty', '£', 'pizza', 2.2, 'http://dummyimage.com/171x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Virginia Wakerobin', '££££', 'french', 3.4, 'http://dummyimage.com/170x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Monte Cerrote Water-willow', '£', 'fast-food', 1.9, 'http://dummyimage.com/171x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Frogbit Buttercup', '££', 'fast-food', 3.2, 'http://dummyimage.com/224x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Ionaspis Lichen', '££', 'steak', 2.3, 'http://dummyimage.com/205x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Alsia Moss', '£', 'chinese', 1.8, 'http://dummyimage.com/245x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Ethiopian Wheat', '££', 'seafood', 3.3, 'http://dummyimage.com/171x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Castle Crags Bellflower', '£', 'steak', 2.3, 'http://dummyimage.com/115x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Dysphania', '£', 'french', 4.6, 'http://dummyimage.com/162x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Flacourtia', '££', 'seafood', 3.9, 'http://dummyimage.com/204x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Smooth Ayenia', '£££', 'seafood', 2.0, 'http://dummyimage.com/215x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Texasplume', '££', 'italian', 3.8, 'http://dummyimage.com/219x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Jawleaf Lupine', '£££', 'chinese', 1.1, 'http://dummyimage.com/110x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Red Baneberry', '££££', 'english', 2.4, 'http://dummyimage.com/125x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Branched Lagophylla', '£', 'english', 2.6, 'http://dummyimage.com/238x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Duss'' Tonguefern', '£££', 'japanese', 3.9, 'http://dummyimage.com/167x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Alaska Blueberry', '££', 'chinese', 1.8, 'http://dummyimage.com/124x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Fringed Beaksedge', '££££', 'chinese', 2.4, 'http://dummyimage.com/217x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Largeleaf Sphagnum', '£££', 'chinese', 1.2, 'http://dummyimage.com/230x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Peirson''s Pincushion', '££££', 'french', 2.6, 'http://dummyimage.com/122x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('White Oak', '££', 'steak', 2.3, 'http://dummyimage.com/232x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Bog Rosemary', '£', 'seafood', 3.6, 'http://dummyimage.com/189x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Blueberry', '£', 'indian', 1.1, 'http://dummyimage.com/208x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pancratium', '££', 'seafood', 2.8, 'http://dummyimage.com/161x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Lemington Hawthorn', '££££', 'pizza', 3.9, 'http://dummyimage.com/132x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Goat Pea', '£££', 'french', 2.6, 'http://dummyimage.com/175x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hop Sedge', '££££', 'steak', 1.9, 'http://dummyimage.com/202x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Desert Columbine', '££££', 'chinese', 3.1, 'http://dummyimage.com/177x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Tropical Woodsorrel', '£', 'seafood', 4.3, 'http://dummyimage.com/139x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Star Sedge', '£', 'indian', 2.2, 'http://dummyimage.com/178x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Parsley Fern', '££', 'fast-food', 4.0, 'http://dummyimage.com/189x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Bullseye Lichen', '£', 'steak', 4.7, 'http://dummyimage.com/245x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lyall''s Polytrichum Moss', '££££', 'indian', 2.8, 'http://dummyimage.com/215x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Fanleaf Fleabane', '££££', 'seafood', 4.4, 'http://dummyimage.com/138x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Wright''s Fabronia Moss', '££££', 'greek', 3.1, 'http://dummyimage.com/154x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('White Arctic Mountain Heather', '£££', 'fast-food', 3.5, 'http://dummyimage.com/220x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Oregon Bentgrass', '£££', 'pizza', 3.6, 'http://dummyimage.com/188x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Areca Palm', '££', 'hot-pot', 4.3, 'http://dummyimage.com/241x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Silverhair Pineapplegrass', '£££', 'hot-pot', 1.1, 'http://dummyimage.com/196x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Nuttall''s Linanthus', '£££', 'indian', 4.3, 'http://dummyimage.com/218x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pineneedle Beardtongue', '£££', 'japanese', 1.9, 'http://dummyimage.com/185x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Black-heads', '£££', 'steak', 3.1, 'http://dummyimage.com/234x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Rhizome Fleabane', '£', 'indian', 1.6, 'http://dummyimage.com/243x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Foxtail Prairie Clover', '£££', 'italian', 2.9, 'http://dummyimage.com/231x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Hecastocleis', '££££', 'english', 3.7, 'http://dummyimage.com/221x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Chaparral Beargrass', '£', 'italian', 3.4, 'http://dummyimage.com/152x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Thintail', '££', 'pizza', 4.2, 'http://dummyimage.com/191x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('San Francisco River Leatherpetal', '££', 'fine-dining', 2.0, 'http://dummyimage.com/113x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Green Withe', '£££', 'pizza', 2.5, 'http://dummyimage.com/176x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Riverbank Wildrye', '££', 'cocktail', 4.9, 'http://dummyimage.com/198x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Texas Crinklemat', '££££', 'italian', 2.4, 'http://dummyimage.com/106x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Blacktorch', '££', 'cocktail', 2.5, 'http://dummyimage.com/131x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hyophila Moss', '££££', 'chinese', 1.1, 'http://dummyimage.com/220x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Greater Yellow Lady''s Slipper', '££', 'hot-pot', 1.9, 'http://dummyimage.com/157x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Elliott''s Milkpea', '££££', 'hot-pot', 1.7, 'http://dummyimage.com/145x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hawai''i Birdnest Fern', '£', 'english', 2.7, 'http://dummyimage.com/197x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Fava Bean', '££', 'pizza', 1.6, 'http://dummyimage.com/160x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Uluhe', '£££', 'chinese', 2.8, 'http://dummyimage.com/238x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('European Cranberrybush', '££', 'fine-dining', 2.9, 'http://dummyimage.com/242x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Longflower Tube Tongue', '££', 'greek', 2.2, 'http://dummyimage.com/127x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Beard Lichen', '£££', 'french', 1.5, 'http://dummyimage.com/132x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Chaenothecopsis Lichen', '£', 'indian', 2.6, 'http://dummyimage.com/245x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Darrow''s Buckwheat', '£££', 'french', 4.6, 'http://dummyimage.com/125x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lanai Labordia', '££', 'italian', 1.3, 'http://dummyimage.com/164x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Rooney''s Pricklypear', '££', 'hot-pot', 3.0, 'http://dummyimage.com/158x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Gymnostomiella Moss', '££££', 'pizza', 1.4, 'http://dummyimage.com/195x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Mountain Sedge', '££', 'michelin', 4.3, 'http://dummyimage.com/197x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pacific Island Clearweed', '£££', 'cocktail', 1.5, 'http://dummyimage.com/236x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Mountain Deathcamas', '£', 'japanese', 4.9, 'http://dummyimage.com/149x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Crested Coralroot', '££££', 'italian', 1.2, 'http://dummyimage.com/108x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Sulphur-flower Buckwheat', '£', 'seafood', 4.3, 'http://dummyimage.com/212x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Bright Copper Homalothecium Moss', '£££', 'greek', 5.0, 'http://dummyimage.com/170x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hairy Smotherweed', '£', 'pizza', 1.7, 'http://dummyimage.com/231x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Wright''s Goldenrod', '££', 'french', 4.0, 'http://dummyimage.com/130x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Montane Dry Rock Moss', '£', 'greek', 2.9, 'http://dummyimage.com/113x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Wandflower', '££', 'fine-dining', 2.7, 'http://dummyimage.com/232x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Smallseed Sandmat', '££', 'indian', 4.9, 'http://dummyimage.com/151x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Dagger Flower', '£££', 'hot-pot', 2.8, 'http://dummyimage.com/206x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hairy Goldenrod', '£££', 'japanese', 3.2, 'http://dummyimage.com/192x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('American Searocket', '£££', 'greek', 3.3, 'http://dummyimage.com/157x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lecidea Lichen', '££', 'fine-dining', 4.5, 'http://dummyimage.com/129x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Common Buckthorn', '£££', 'french', 1.9, 'http://dummyimage.com/217x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Beet', '££££', 'french', 3.5, 'http://dummyimage.com/129x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Mannagrass', '£', 'seafood', 3.4, 'http://dummyimage.com/222x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Map Lichen', '££', 'indian', 3.9, 'http://dummyimage.com/145x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Moth Fanpetals', '£', 'cocktail', 2.2, 'http://dummyimage.com/205x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Longstem Milkwort', '£', 'chinese', 4.6, 'http://dummyimage.com/191x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Virginia Wakerobin', '££££', 'english', 4.6, 'http://dummyimage.com/126x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pore Lichen', '££', 'pizza', 1.4, 'http://dummyimage.com/114x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hybrid Oak', '££', 'indian', 4.3, 'http://dummyimage.com/153x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Stout Rush', '££', 'fast-food', 4.5, 'http://dummyimage.com/231x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Field Mustard', '£££', 'steak', 2.2, 'http://dummyimage.com/152x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hawkweed', '£', 'english', 2.7, 'http://dummyimage.com/163x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Greene''s Rush', '££', 'seafood', 1.2, 'http://dummyimage.com/185x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Spring Thistle', '£', 'greek', 2.7, 'http://dummyimage.com/101x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Haplohymenium Moss', '££', 'fine-dining', 3.3, 'http://dummyimage.com/183x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Death Valley Phacelia', '£', 'greek', 3.8, 'http://dummyimage.com/247x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Hawai''i Korthal Mistletoe', '££££', 'greek', 1.6, 'http://dummyimage.com/158x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Kidney Lichen', '££££', 'fast-food', 1.8, 'http://dummyimage.com/198x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Poet''s Jasmine', '££££', 'italian', 2.5, 'http://dummyimage.com/240x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Thurovia', '££', 'english', 4.7, 'http://dummyimage.com/214x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Sauropus', '££', 'italian', 1.4, 'http://dummyimage.com/166x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Bigleaf Magnolia', '£££', 'italian', 3.4, 'http://dummyimage.com/215x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Graceful Wattle', '£', 'greek', 2.1, 'http://dummyimage.com/186x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Lagenocarpus', '££££', 'pizza', 1.3, 'http://dummyimage.com/132x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Narrowpod Sensitive Pea', '££££', 'french', 2.5, 'http://dummyimage.com/248x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pohil''s Milkvetch', '££££', 'french', 4.9, 'http://dummyimage.com/119x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Nevada Cryptantha', '£', 'greek', 3.7, 'http://dummyimage.com/212x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Chestnut Vine', '£££', 'english', 1.1, 'http://dummyimage.com/244x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Looseflower Alpine Sedge', '£££', 'seafood', 1.8, 'http://dummyimage.com/135x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Niterwort', '£', 'steak', 2.2, 'http://dummyimage.com/231x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Aleutian Draba', '£££', 'italian', 1.1, 'http://dummyimage.com/217x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Wullschlaegelia', '£££', 'french', 4.8, 'http://dummyimage.com/218x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Canadian Sandspurry', '££££', 'pizza', 4.8, 'http://dummyimage.com/229x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Slender False Pennyroyal', '£', 'pizza', 1.1, 'http://dummyimage.com/200x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Scouler''s Willow', '££££', 'fast-food', 2.5, 'http://dummyimage.com/141x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Glossy Privet', '£', 'fine-dining', 2.0, 'http://dummyimage.com/166x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Bingen Lupine', '£££', 'greek', 3.6, 'http://dummyimage.com/112x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Redwood Lily', '££', 'seafood', 1.4, 'http://dummyimage.com/174x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Australian Sundew', '££', 'steak', 2.9, 'http://dummyimage.com/139x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Bluehearts', '££', 'french', 3.6, 'http://dummyimage.com/224x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Bedstraw', '££', 'pizza', 4.3, 'http://dummyimage.com/224x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Thunberg''s Amaranthus', '£', 'seafood', 2.6, 'http://dummyimage.com/168x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Tamarind', '£', 'chinese', 3.0, 'http://dummyimage.com/104x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pacific Mistletoe', '£', 'japanese', 1.9, 'http://dummyimage.com/171x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Orange Wall Lichen', '£££', 'fast-food', 4.2, 'http://dummyimage.com/232x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('West''s Flax', '£', 'italian', 4.6, 'http://dummyimage.com/226x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Roald''s Locoweed', '£', 'english', 2.5, 'http://dummyimage.com/213x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Panamint Mountain Lupine', '££££', 'english', 4.7, 'http://dummyimage.com/150x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Orphniospora Lichen', '££', 'italian', 3.0, 'http://dummyimage.com/174x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Muriti', '£££', 'fine-dining', 2.6, 'http://dummyimage.com/226x100.png/cc0000/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Tennessee Ironweed', '££££', 'hot-pot', 3.4, 'http://dummyimage.com/116x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Davall''s Pottia Moss', '£', 'greek', 2.5, 'http://dummyimage.com/232x100.png/5fa2dd/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Pseudophoenix', '££', 'indian', 3.9, 'http://dummyimage.com/100x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Orange Lichen', '££', 'cocktail', 1.5, 'http://dummyimage.com/215x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Black Cherry', '£', 'french', 1.7, 'http://dummyimage.com/144x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Eastern Whiteflower Beardtongue', '££', 'fine-dining', 3.2, 'http://dummyimage.com/232x100.png/ff4444/ffffff');
insert into restaurants (name, price, type, rating, image_source) values ('Southeastern Annual Saltmarsh Aster', '££££', 'italian', 4.2, 'http://dummyimage.com/230x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('California Pleuridium Moss', '£££', 'michelin', 3.4, 'http://dummyimage.com/126x100.png/dddddd/000000');
insert into restaurants (name, price, type, rating, image_source) values ('Gregg''s Sensitive Pea', '££££', 'seafood', 3.8, 'http://dummyimage.com/165x100.png/dddddd/000000');
